Collect Optional Email from Applicant
hmcts/fis-ds-web pull request #153
Opened 2022-05-31 14:00 UTC by RonanCog

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-06-08 15:08 UTC, SangeethaPonnusamy approved these changes

2022-06-08 15:40 UTC, yogendraU requested changes

2022-06-08 15:40 UTC, yogendraU commented on README.md
Is this file change required?

2022-06-08 15:40 UTC, yogendraU commented on README.md
> +## Running with Docker
Is this change required?

2022-06-08 16:04 UTC, Murshadhaque commented on README.md
> +## Running with Docker
reverted

2022-06-08 16:05 UTC, Murshadhaque commented on README.md
reverted

2022-06-08 16:13 UTC, yogendraU approved these changes

2022-06-08 16:15 UTC, hmcts-kodatala approved these changes
Ok

2022-06-09 09:25 UTC, saravanakumar-palanichamy approved these changes

2022-06-09 09:48 UTC, merged